package:
  name: rmc_tools
  version: 0.0.1

build:
  number: 2

source:
  path: d:\Dev\rmc_adv_tools\

requirements:
  build:
    - numpy >=1.18.5
    - matplotlib >=3.2.2
    - scipy >=1.6.2
  run:
    - python >=3.6.0
    - numpy >=1.18.5
    - matplotlib >=3.2.2
    - scipy >=1.6.2

about:
  home: https://code.ornl.gov/zyroc1990/utilities/tree/master/rmc_tools
  license: GPL
  license_file: LICENSE.txt
  summary: Tools for processing and analyzing RMC configuration.
