package:
  name: sofq_calib
  version: 1.0.1

build:
  number: 9

source:
  path: /Users/y8z/Dev/rmc_adv_tools/sofq_calib_mac

requirements:
  build:
    - python >=3.6.0
    - wxpython >=4.0
    - numpy
    - matplotlib >=3.0
  run:
    - python >=3.6.0
    - wxpython >=4.0
    - numpy
    - matplotlib >=3.0

about:
  home: https://https://code.ornl.gov/zyroc1990/Utilities/tree/master/sofq_calib
  license: GPL
  license_file: LICENSE.txt
  summary: Tools for calibrating S(Q) against Bragg data.
